[package]
name = "mntk"
description = "Media Naming Toolkit: name local media files using metadata sources"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
mntk-core.workspace = true
mntk-source-omdb.workspace = true
ratatui.workspace = true
thiserror.workspace = true
